version: '3.8'

services:
  rust-app:
    build: .
    ports:
      - "3333:3333"
    environment:
      - RUST_LOG=info
      - DATABASE_URL=postgresql://postgres:password@db:5432/rust_app
    depends_on:
      - db
    volumes:
      - ./src:/app/src
      - ./Cargo.toml:/app/Cargo.toml
      - ./Cargo.lock:/app/Cargo.lock
    restart: unless-stopped

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=rust_app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  postgres_data: